name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - wandb
      - omegaconf
      - pandas
      - scikit-learn
      - matplotlib
      - plotly
      - pillow
      - mlflow