name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - wandb
      - hydra-joblib-launcher
      - mlflow
      - hydra-core
      - requests
