wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.15.12
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1698649674.724335
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.11.6
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
